### ISSUE TITLE
Automatic trigger new builds

### ISSUE THREAD

**Issue by bobvandevijver** [cloudflare/docker-phan#10]
As discussed in #7, this image is not updated at a regular interval. However, as Phan is quite active in development, it should create more images more often.

Automatic builds should be possible with Travis CI (and possibly for free).

Edit: Currently I'm working in my fork to add Travis Support (https://github.com/Kick-In/docker-phan/pull/1), which is already building the newest edge image. Travis has indeed a free option for opensource project, and also supports cron builds.
When finished, I will submit a PR for this repository, but someone here should have configured travis first for it to work correctly.

**Comment by terinjokes** [comment]
@bobvandevijver Yeah, I've been meaning to setup publish from Travis (the builder script should already have the work done). I can setup Travis's timer support too.

**Comment by bobvandevijver** [comment]
Fixed with 4b865f90b27c8014a3e0e6e2c11616ed6a348d2c.

**Comment by terinjokes** [comment]
I've enabled this to run weekly (looks like it will run early Friday morning UTC). If Phan development picks up, I don't mind moving it to daily.

Until travis-ci/travis-ci#7181 is resolved in any fashion, we'll be doing builds, running tests, and publishing all supported versions. It's less than ideal, but the matrix runs in about 8 minutes, so it's not too terrible.

This does mean the image tags will change (they do anyways on non-cron builds), so if you're using docker-phan in a continuous testing environment, I highly recommend specifying the specific hashes.

Bedankt @bobvandevijver!
