### ISSUE TITLE
Doesn't work with checkstyle output mode

### ISSUE THREAD

**Issue by darthsteven** [cloudflare/docker-phan#4]
When I tried to use this with the checkstyle output mode, it complained that the DOMDocument class was missing, presumably because the version of PHP installed in this image is so minimal that it doesn't include the DOM extension.

**Comment by darthsteven** [comment]
The error I'm seeing is:

> $ phan --output-mode checkstyle -b index.php 
> Error: Class 'DOMDocument' not found in /opt/phan/src/Phan/Output/Printer/CheckstylePrinter.php:36
> Stack trace:
> #0 /opt/phan/src/Phan/Phan.php(309): Phan\Output\Printer\CheckstylePrinter->flush()
> #1 /opt/phan/src/Phan/Phan.php(224): Phan\Phan::display()
> #2 /opt/phan/src/phan.php(43): Phan\Phan::analyzeFileList(Object(Phan\CodeBase), Array)
> #3 /opt/phan/phan(2): require_once('/opt/phan/src/p...')
> #4 {main}

**Comment by terinjokes** [comment]
@darthsteven OK, I'll expand the extensions installed.

**Comment by darthsteven** [comment]
Please see my PR before you do! #5

**Comment by darthsteven** [comment]
Looks like this should be working now. Thanks!
