### ISSUE TITLE
How to get the latest Phan version

### ISSUE THREAD

**Issue by bobvandevijver** [cloudflare/docker-phan#7]
Hi, 

I'm not sure how to get the latest phan version installed: currently it looks like I'm quite some commits behind. I start the check by running:

```
docker run --rm -v $PWD:/mnt/src cloudflare/phan:latest -k tests/phan/config.php
```

Can you tell me how I can get Phan to the latest version?

**Comment by terinjokes** [comment]
@bobvandevijver Unfortunately, releases here aren't automatically triggered by releases from Etsy. I'll look into triggering releases more often.

As of a few minutes ago:

* `cloudflare/phan:0.7` has been published
* `cloudflare/phan:latest` now points at version 0.7
* `cloudflare/phan:edge` is now https://github.com/etsy/phan/commit/a1025bc6e94a1104cd70201be3e2b87333e27f61.

**Comment by bobvandevijver** [comment]
The issue I had with Phan is now solved, so thank you very much!
